server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/short_url
    username: root
    password: 123456

base:
  path: http://minxie.space/a/